config/routes.rb
Myapp::Application.routes.draw do

  resources :infos, :only => ['show'] do
    post :comment, :on => :member
    get :top, :on => :collection

  end
  resources :wormholes, :only => ['index', 'show'] do
    get :q, :on => :collection
    post :comment, :on => :member
  end

  root :to => 'home#index'

end

app/models/climate.rb
class Climate
  include MongoMapper::Document
  key :name, String
  key :cls, Integer
  key :affects, Array

end

app/models/comment.rb
class Comment
  include MongoMapper::Document
  key :body, String
  timestamps!

  belongs_to :commentable, :polymorphic => true

end

app/models/info.rb
class Info
  include MongoMapper::Document

  many :comments, :as => :commentable
  key :name, String
  key :content, String
  timestamps!

  def rc
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    markdown.render(content)
  end

end

app/models/user.rb
class User
  include MongoMapper::Document

  key :email, String
  key :name, String

end

app/models/wormhole.rb
# encoding: UTF-8
class Wormhole
  include MongoMapper::Document
  many :comments, :as => :commentable
  key :name, String
  key :scs, Array
  key :planets, Array
  key :climate, String
  key :cls, Integer
  timestamps!

  def trans_pl(p, i)
    p = p.gsub 'Planet', "行星#{i}"
    p = p.gsub 'Barren', '贫瘠'
    p = p.gsub 'Plasma', '等离子'
    p = p.gsub 'Temperate', '温和'
    p = p.gsub 'Gas', '气体'
    p = p.gsub 'Lava', '熔岩'
    p = p.gsub 'Ice', '冰体'
    p = p.gsub 'Oceanic', '海洋'
    p = p.gsub 'Storm', '风暴'
  end

  def get_climate_affects
    Climate.where(:name => self.climate, :cls => self.cls).first.affects
  end

  def get_info
    require 'open-uri'
    doc = Nokogiri::HTML(open("http://www.staticmapper.com/index.php?system="+self.name))
    lists = doc.css('.categoryitems>li')
    if lists.count == 0
      return false
    else
      planet = ''
      i = 0
      lists.each do |lst|
        if lst.attributes["class"].value=='moonpad '
          planet += ': 卫星 X '+lst.css('li').count.to_s
        else
          if planet.length > 0
            i += 1
            planet = trans_pl(planet, i)
            self.planets.push(planet)
            self.save
          end
          planet = lst.css('img')[0].attributes['alt'].value
        end
      end
      if planet.length > 0
	i += 1
	planet = trans_pl(planet, i)
	self.planets.push(planet)
	self.save
      end
      return true
    end
  end

  def scs_in_string
    scs.reduce{|a,b|"#{a},#{b}"}
  end

  def scs_in_string=(s)
    self.scs = s.split(",")
  end

  def rpi
    false
  end

  def rpi=(flag)
    if flag.to_s=="1"
      puts flag
      puts "Planets Info Reseted"
      self.planets = []
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.sort(:created_at.desc)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end

  def comment
    @info = Info.find(params[:id])
    @info.comments.create(body: params[:body])
    redirect_to @info
  end

end

app/controllers/wormholes_controller.rb
# encoding: UTF-8
class WormholesController < ApplicationController
  # GET /wormholes
  # GET /wormholes.json
  def index
    if params[:name]
      redirect_to '/wormholes/'+params[:name]
      return
    end
    @lac = Comment.sort(:created_at.desc).where(:commentable_type => 'Wormhole').limit(20)
    @infos = Info.sort(:created_at.desc).all
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  

  def q
    name = params[:name].upcase
    @whs = Wormhole.where(:name => /^#{name}/).fields(:name).all
    respond_to do |format|
      format.json {render json: @whs }
    end
  end

  def comment
    @wh = Wormhole.find_by_name(params[:id].upcase)
    @wh.comments.create(body: params[:body])
    redirect_to "/wormholes/#{params[:id]}"
  end

  # GET /wormholes/1
  # GET /wormholes/1.json
  def show
    @wh = Wormhole.find_by_name(params[:id].upcase)
    if (not @wh)
      @error = true
    elsif (@wh.planets.count == 0) or (params[:forceclear])
      @wh.planets.clear
      @wh.get_info
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wh }
    end
  end

  # GET /wormholes/new
  # GET /wormholes/new.json
  def new
    @wormhole = Wormhole.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wormhole }
    end
  end

  # GET /wormholes/1/edit
  def edit
    @wormhole = Wormhole.find_by_name(params[:id].upcase)
  end

  # POST /wormholes
  # POST /wormholes.json
  def create
    @wormhole = Wormhole.new(params[:wormhole])

    respond_to do |format|
      if @wormhole.save
        format.html { redirect_to "/wormholes/#{@wormhole.name}", notice: 'Wormhole was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /wormholes/1
  # PUT /wormholes/1.json
  def update
    @wormhole = Wormhole.find(params[:id])

    respond_to do |format|
      if @wormhole.update_attributes(params[:wormhole])
        format.html { redirect_to "/wormholes/#{@wormhole.name}", notice: 'Wormhole was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /wormholes/1
  # DELETE /wormholes/1.json
  def destroy
    @wormhole = Wormhole.find(params[:id])
    @wormhole.destroy

    respond_to do |format|
      format.html { redirect_to wormholes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/wormholes_helper.rb
module WormholesHelper
end

app/views/home/index.html.haml
.row
  .span9.offset1.hero
    %h1 欢迎从远方星系来的客人
    %p 这是个人搭建的方便EVE玩家的工具网站。
    %p 如果有什么意见或反馈，欢迎给游戏id: SQRH留言，
  .clearfix
  .span9.offset1.hero
    = link_to '虫洞信息查询', '/wormholes'
  .clearfix
  .span9.offset1.hero
    %h3 Bugs/Fixtures
    %ul
      %li 2013.04.25 重启更新，添加虫洞攻略。
      

app/views/infos/_form.html.haml
= form_for @info do |f|
  - if @info.errors.any?
    #error_explanation
      %h2= "#{pluralize(@info.errors.count, "error")} prohibited this info from being saved:"
      %ul
        - @info.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/infos/edit.html.haml
%h1 Editing info

= render 'form'

= link_to 'Show', @info
\|
= link_to 'Back', infos_path

app/views/infos/index.html.haml
- model_class = Info
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
.span9.offset1
  %ul.infos-list
    - @infos.each do |info|
      %a{:href=> info_url(info)}
        %li
          .info-time= l(info.created_at, :format => :short)
          .info-name= info.name
          .info-comments-count= info.comments.count
          .clearfix
.clearfix

app/views/infos/new.html.haml
%h1 New info

= render 'form'

= link_to 'Back', infos_path

app/views/infos/show.html.haml
- model_class = Info
.page-header
  .span8
    %h1=@info.name
  .span2
    %button#toggle-bg.btn.btn-large 不显示背景
  .clearfix
.row
  .offset1.span9
    =raw @info.rc
  .clearfix

.row
  .span9.offset1
    %form.comment-form{action: "/infos/#{@info.id}/comment", method: 'POST'}
      %textarea.span6{name: "body"}
      %button.btn.btn-large.btn-primary 发留言
    .clearfix
    %ul.comments
      - @info.comments.sort(:created_at.desc).each do |cmt|
        %li
          .time= l cmt.created_at
          .body= cmt.body
          .clearfix

app/views/infos/top.html.haml
.page-header
  %h1 置顶信息

.row
  .offset1.span9
    暂无，如有需要请联系游戏内发信：SQRH

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EVE"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"

  %body
    #navtop
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") EVE
          .container.nav-collapse
            %ul.nav
              %li= link_to t('.home'), "/"
              %li= link_to t('.wormholes'), "/wormholes"
    %a#gototop{:href => '#navtop'} 
      %i.icon-arrow-up
    .container

      .row
        .span12
          .main-part
            = yield
    
      %footer
        %p 
          =link_to '©Sqrh 2013', 'http://www.sqrh.net'
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/wormholes/_form.html.haml
= form_for @wormhole, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, "Name", :class => 'control-label'
    .controls
      = f.text_field :name
  .control-group
    = f.label :cls, "Class", :class => 'control-label'
    .controls
      = f.text_field :cls
  .control-group
    = f.label :scs_in_string, "Static Links", :class => 'control-label'
    .controls
      = f.text_field :scs_in_string
  .control-group
    = f.label :climate, "Climate", :class => 'control-label'
    .controls
      = f.text_field :climate
      %span.help_inline
        可选： 
        = Climate.all.map{|a|a.name}.uniq.reduce{|a,b| "#{a} #{b}"}
  .control-group
    = f.label :rpi, "Reset Planet Info?", :class => 'control-label'
    .controls
      = f.check_box :rpi
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), wormholes_path, :class => 'btn'

app/views/wormholes/comments.haml
.hero
  %h3 最新20条虫洞留言
  .row
    .span10
      %ul.comments
        - @lac.each do |cmt|
          %li
            .time
              %p= l cmt.created_at
              %p
                发布于 
                = link_to cmt.commentable.name, "/wormholes/#{cmt.commentable.name}"
            .body= cmt.body
            .clearfix

app/views/wormholes/edit.html.haml
- model_class = Wormhole
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/wormholes/index.html.haml
- model_class = Wormhole
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
.row
  .span3
  .span6
    %form.form-search
      %input.input-xlarge.search-query.typeahead.wh{type: "text", name: "name", placeholder: "输入星系", "data-provide"=> "typeahead", autocomplete: "off"}
      %button.btn{type: "submit"}
        %i.icon-search
        =t '.search'
  .span3
  .clearfix
.hero
  %h3 相关信息
  .row
  .span10
    %ul.infos-list
      %li
        %a{:href=> "/infos/top"}
          .info-time 置顶
          .info-name -----广告位招租-----
          .clearfix

      - @infos.each do |info|
        %li
          %a{:href=> info_url(info)}
            .info-time= l(info.created_at, :format => :short)
            .info-name= info.name
            .info-comments-count
              = info.comments.count
              %i.icon-comment.icon-white
            .clearfix
  .clearfix
  

app/views/wormholes/new.html.haml
- model_class = Wormhole
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/wormholes/show.html.haml
- model_class = Wormhole
.page-header
  .span6
    %h1=params[:id]
    %h4=@wh.cls.to_s+'级虫洞' unless @error
  .span4
    %form.form-search{action: '/wormholes/'}
      %input.input-medium.search-query.typeahead.wh{type: "text", name: "name", placeholder: "输入星系", "data-provide"=> "typeahead", value: params[:id], autocomplete: "off"}
      %button.btn{type: "submit"}
        =t '.search'
  .clearfix

.row
  .span5.offset1
    -if @error
      没有关于该星系的信息，请检查是否输入了正确的编号
    -else
      %h3 行星信息
      %ul
        -@wh.planets.each do |pl|
          %li=pl
  .span2.offset1
    -unless @error
      .climate
        %h3 天象
        = @wh.climate

        %h5 对船只影响如下：单位为%
        - if @wh.climate.length>0
          %ul
            - @wh.get_climate_affects.each do |af|
              %li= af
        - else
          %p 无
      .static-connection
        %h3 永连
        - if @wh.scs.count > 0
          %ul
            - @wh.scs.each do |sc|
              %li= sc
          %h5 0和00都指00地区，其他数字则表示洞的等级。
        - else
          %p 无
  .clearfix

-unless @error
  .row
    .span8.offset1
      %form.comment-form{action: "/wormholes/#{@wh.name}/comment", method: 'POST'}
        %textarea.span6{name: "body"}
        %button.btn.btn-large.btn-primary 发留言
      .clearfix
      %ul.comments
        - @wh.comments.sort(:created_at.desc).each do |cmt|
          %li
            .time= l cmt.created_at
            .body= cmt.body
            .clearfix